name: Build and Deploy Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.1.1

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-ocaml-docs-${{ hashFiles('**/*.opam') }}

    - name: Install dependencies
      run: |
        opam install dune odoc -y
        opam install . -y

    - name: Build documentation
      run: |
        eval $(opam env)
        dune build @doc
        mkdir -p docs
        cp -r _build/default/_doc/_html/* docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
