name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.1.1

    - name: Cache OPAM
      uses: actions/cache@v4
      with:
        path: ~/.opam
        key: ${{ runner.os }}-ocaml-${{ hashFiles('**/*.opam') }}

    - name: Install dependencies
      run: |
        opam install dune -y
        opam install . --with-test -y

    - name: Build and Test
      run: |
        opam exec -- dune build
        opam exec -- dune runtest
